### ISSUE TITLE
Census demographics API mismatch still breaks primary path after #197 (unexpected keyword: dataset)

### ISSUE THREAD

**Issue by dheerajchand** [siege-analytics/siege_utilities#200]
## Summary
`get_demographics()` is still failing in active Databricks smoke runs with:

`get_demographics() got an unexpected keyword argument "dataset"`

Issue #197 improved boundary diagnostics, but the primary Census retrieval path is not fully solved for downstream users because demographics retrieval is still incompatible at call boundary.

## Evidence
From current smoke-job outputs (2020 + 2023):
- `boundary_source`: `legacy_tiger_fallback`
- primary path diagnostics report failure before successful fallback
- demographics step error text includes: `unexpected keyword argument "dataset"`

Observed successful run IDs (via fallback, not full primary):
- 2020 run: `1000798981561618`
- 2023 run: `19055346562771`

## Why this matters
Closing #197 can imply boundary/Census retrieval is complete, but in production-style notebook usage we still cannot rely on the primary path end-to-end.

## Requested fix
1. Make `get_demographics` signature-compatible across supported call styles (accept/normalize `dataset` and expected variables args).
2. Add unit tests that lock compatibility for both current and legacy invocation forms.
3. Add an integration test that mirrors Databricks notebook usage and asserts:
   - primary path succeeds without fallback
   - demographics payload is returned for both 2020 and 2023 smoke cases.
4. Document migration guidance if any parameter names changed intentionally.

## Acceptance criteria
- No `unexpected keyword argument "dataset"` in smoke outputs.
- Primary path can produce boundaries + demographics without legacy fallback.
- Regression tests cover both years and both call signatures.

**Comment by dheerajchand** [comment]
Started fresh Databricks runtime validation on latest release in `dev` environment:
- 2020 run: `968937672484668`
- 2023 run: `174221666092520`

Both are currently `RUNNING`. I will post terminal-state outputs for signature-error verification and primary-path/fallback behavior.

**Comment by dheerajchand** [comment]
Databricks runtime validation after latest release still reproduces the same error in notebook output:

Runs (both TERMINATED/SUCCESS at job level):
- 2020 run `968937672484668` (task `347945599027392`)
- 2023 run `174221666092520` (task `252746179356591`)

Result payload in both runs still includes:
`"error": "get_demographics() got an unexpected keyword argument "dataset""`

Additional context from same payload:
- `boundary_source: legacy_tiger_fallback`
- fallback rows were loaded (254 source rows, 250 output rows)

So in this runtime, the convenience-call signature mismatch is still present at execution time even though v3.3.3 code looks correct at source. This suggests either:
1) runtime is not actually importing v3.3.3, or
2) another call path/module still exposes the old signature.

I can add a diagnostic print in notebook to emit `siege_utilities.__version__` + `inspect.signature(get_demographics)` at runtime to disambiguate immediately.
